### ISSUE TITLE
Removed from plugin manager ?

### ISSUE THREAD

**Issue by tvixen** [ntoff/OctoPrint-ExtraDistance#1]
Hi there
The plugin is no longer available via plugin manager... Why ?

**Comment by ntoff** [comment]
I removed all my plugins as I won't have time to ensure compatibility with future octoprint versions. The code will remain on github, but probably won't be updated to take advantage of the new granular permissions that were being added to octoprint, or to fix any bugs that might appear.

If someone wants to fork it and take over, they're more than welcome to do so.
